### ISSUE TITLE
Fails if registering my own`template` component

### ISSUE THREAD

**Issue by jevets** [jenstornell/kirby-init-controller#2]
If I've registered my own `template` component, there are conflicts. 

Either this plugin is called and my custom template component is never run, or my template component runs and the init-controller is never run.

But, one could build-in the same principal as this into his own custom component.

**Comment by jevets** [comment]
This issue is mostly informational, feel free to close it.

**Comment by jenstornell** [comment]
I have a discussion in the forum about it. :)

https://forum.getkirby.com/t/allow-multiple-plugins-to-register-the-same-component/4802/6
